"""add_resume_analysis_fields

Revision ID: adc6ba2d24b0
Revises: bfe001ce3c12
Create Date: 2026-06-11 09:53:02.098193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc6ba2d24b0'
down_revision: Union[str, Sequence[str], None] = 'bfe001ce3c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
