"""add_user_profiles_table

Revision ID: d34983aee9ed
Revises: d404281def91
Create Date: 2026-07-26 22:19:05.790657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd34983aee9ed'
down_revision: Union[str, Sequence[str], None] = 'd404281def91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('preferred_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
