"""add_coding_session_report_fields

Revision ID: d9a5a413f264
Revises: 74b72a3e12a7
Create Date: 2026-06-27 13:56:00.577652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9a5a413f264'
down_revision: Union[str, Sequence[str], None] = '74b72a3e12a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_interview_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('coding_interview_sessions', sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coding_interview_sessions', sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coding_interview_sessions', sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coding_interview_sessions', 'recommendations')
    op.drop_column('coding_interview_sessions', 'improvements')
    op.drop_column('coding_interview_sessions', 'strengths')
    op.drop_column('coding_interview_sessions', 'summary')
    # ### end Alembic commands ###
