"""add_resume_intelligence

Revision ID: ef93e690670b
Revises: de815e48e0eb
Create Date: 2026-06-17 09:28:55.965145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef93e690670b'
down_revision: Union[str, Sequence[str], None] = 'de815e48e0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "resumes",
        sa.Column(
            "ats_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "resumes",
        sa.Column(
            "strengths",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
    )

    op.add_column(
        "resumes",
        sa.Column(
            "weaknesses",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
    )

    op.add_column(
        "resumes",
        sa.Column(
            "missing_skills",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
    )

    op.add_column(
        "resumes",
        sa.Column(
            "recommendations",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'recommendations')
    op.drop_column('resumes', 'missing_skills')
    op.drop_column('resumes', 'weaknesses')
    op.drop_column('resumes', 'strengths')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
